[package]
name = "ttl-file"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "5.0"
env_logger = "0.9"
log = "0.4"
walkdir = "2.3"
humantime = "2.1"

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
